In [4]:
#Key-features 
#1. ndarray (N-dimensional Array) : The ndarray is a central data structure in NumPy. It is a homogeneous array of fixed-size elements, supporting various data types

import numpy as np

arr = np.array([1,2,3])
arr


array([1, 2, 3])

In [5]:
np.__version__

'1.24.4'

In [7]:
#Vectorized Operations:
# - Numpy allows for vectorize operations where operations are performed element wise on entire arrays leading to efficient and concise code
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)

[5 7 9]


In [9]:
#Broadcasting :Broadcasting allows NumPy to perform operations on arrays of different shapes and sizes, making it easier to work with data of varying dimensions.


arr = np.array([[1,2,3],[4,5,6]])
scalar = 2
result = arr*scalar
print(result)

[[ 2  4  6]
 [ 8 10 12]]


In [11]:
#UNiversal functions(ufunc):Universal functions are functions that operate element-wise on arrays. They provide a convenient way to perform mathematical operations on entire arrays without the need for explicit loops.

arr = np.array([1,2,3])
squared = np.square(arr)
print(squared)

[1 4 9]


In [13]:
#linear algebra operations:NumPy provides a rich set of linear algebra functions, including matrix multiplication, eigenvalue decomposition, singular value decomposition, and more.

#linear algebra operations

matrix = np.array([[1,2],[3,4]])
#
inverse = np.linalg.inv(matrix)
print(inverse)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [15]:
#Random module : generation of random numbers 

random_array = np.random.rand(3,3)
print(random_array)

[[0.16361987 0.93005503 0.8069389 ]
 [0.30524905 0.81140834 0.08689013]
 [0.95575613 0.29544306 0.65472017]]


In [16]:
#memory layout : NumPy provides options to control the memory layout of arrays, allowing for optimization of performance.

arr = np.array([[1,2],[3,4]],order = 'F')# Fortran order (column-major)
print(arr)

[[1 2]
 [3 4]]


In [19]:
#advanced indexing

arr = np.array([[1,2],[3,4],[5,6]])
indices = np.array([0,1,0])
result = arr[np.arange(3),indices] # select elements using interger array indexing
print(result)

[1 4 5]


In [22]:
#structured arrays : NumPy allows you to define structured arrays with multiple fields, similar to a database table.
#np.dtype is used to define the data type for the structured array. The data type is specified as a list of tuples, where each tuple represents a field in the structured array.
#'S10' specifies a string of maximum length 10, and int specifies an integer.

dt = np.dtype([('name','S10'),('age',int)])
data = np.array([('John',25),('Jane',30)],dtype = dt)
print(data)

[(b'John', 25) (b'Jane', 30)]


In [23]:
numpy? #documentation

In [ ]:
#Some more basics and practices on numpy library

In [8]:
lst=list(range(10))
lst

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [9]:
type(lst[3])

int

In [10]:
# conversion of list item int into string type
lst2=[str(c) for c in lst] 
lst2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [11]:
lst3=[True,'23',2.0,4]
type(lst3)

list

In [12]:
[type(item) for item in lst3]

[bool, str, float, int]

In [14]:
# fixed type array in python
import array
lst=list(range(20))
a=array.array('i',lst) #  here 'i' is type code which indicates the content are intergers
a

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [17]:
# creating array from python lists
a=numpy.array([1,2,34,5,7])
a

array([ 1,  2, 34,  5,  7])

In [18]:
numpy.array([2.0,3,6,9]) # here is the import concept
# id data types doesn't match then numpy will upcast if possible (integers are upcast to floating point)

array([2., 3., 6., 9.])

In [19]:
# we can set the data types
numpy.array([2,3,5,7,8],dtype='float')

array([2., 3., 5., 7., 8.])

In [20]:
# unlike python list ,numpy array explicitly be multidimensional
numpy.array([range(i,i+3) for i in [2,4,6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [21]:
numpy.array(range(1,10))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# creating array from scratch
numpy.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [24]:
numpy.ones((3,5)) # 3*5 floating array filled with 1s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
numpy.zeros(10) # by default=float

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
# create a 3*5 array filled with 3.14
numpy.full((3,5),3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [29]:
# Create an array filled with a linear sequence
 # Starting at 0, ending at 20, stepping by 2
 # (this is similar to the built-in range() function)
import numpy as np
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [30]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [31]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3,3))

array([[0.79096732, 0.36185014, 0.6122589 ],
       [0.88239945, 0.21311223, 0.58174913],
       [0.34993922, 0.65861466, 0.87695616]])

In [32]:
# Create a 3x3 array of normally distributed random values
# here is mean= 0 and standard deviation=1
np.random.normal(0,1,(3,3))

array([[ 0.67610433,  1.81611459,  1.05972754],
       [-0.64926016, -0.24948995,  0.99789425],
       [ 0.89871459,  0.78833084, -1.13132986]])

In [33]:
# create a 3*3 array of  random integer betwn 1,10
np.random.randint(1,10,(3,3))

array([[1, 7, 1],
       [5, 4, 4],
       [5, 9, 2]])

In [34]:
np.eye(3) # eye() is used to create identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [35]:
np.random.randint(1,10,(3,3))

array([[7, 8, 3],
       [7, 3, 9],
       [6, 7, 8]])

In [36]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)    

array([1., 1., 1.])

In [38]:
# notice a point
np.zeros(10,dtype='int16')


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [39]:
np.zeros(9,dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [ ]:
'''bool_ Boolean (True or False) stored as a byte
int_ Default integer type (same as C long; normally either int64 or int32)
intc Identical to C int (normally int32 or int64)
intp Integer used for indexing (same as C ssize_t; normally either int32 or int64)
int8 Byte (–128 to 127)
int16 Integer (–32768 to 32767)
int32 Integer (–2147483648 to 2147483647)
int64 Integer (–9223372036854775808 to 9223372036854775807)
uint8 Unsigned integer (0 to 255)
uint16 Unsigned integer (0 to 65535)
uint32 Unsigned integer (0 to 4294967295)
uint64 Unsigned integer (0 to 18446744073709551615)
float_ Shorthand for float64
float16 Half-precision float: sign bit, 5 bits exponent, 10 bits mantissa
float32 Single-precision float: sign bit, 8 bits exponent, 23 bits mantissa
float64 Double-precision float: sign bit, 11 bits exponent, 52 bits mantissa
complex_ Shorthand for complex128
complex64 Complex number, represented by two 32-bit floats
complex128 Complex number, represented by two 64-bit floats'''

In [40]:
# the basic of numpy array
# 1. Attribute of arrays:
#    --size,shape,memory consumption,and data type of array
# 2.indexing of array:
#   ---getting and setting the value of individual array elements
# 3.slicing of array:
#   ---getting and setting amaller subarrays within a larger array
# 4.reshaping of array:
#   ---chnaging the shape of a given array
# 5.joining and splitting of array:
#    ---combining multiple arrays into one ,and splitting one into many

In [42]:
np.random.seed(0) # seed for reproductibility
x1=np.random.randint(10,size=6)
x1

array([5, 0, 3, 3, 7, 9])

In [43]:
x2=np.random.randint(10,size=(3,4))
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [45]:
x3=np.random.randint(10,size=(3,4,5))
x3

array([[[4, 3, 4, 4, 8],
        [4, 3, 7, 5, 5],
        [0, 1, 5, 9, 3],
        [0, 5, 0, 1, 2]],

       [[4, 2, 0, 3, 2],
        [0, 7, 5, 9, 0],
        [2, 7, 2, 9, 2],
        [3, 3, 2, 3, 4]],

       [[1, 2, 9, 1, 4],
        [6, 8, 2, 3, 0],
        [0, 6, 0, 6, 3],
        [3, 8, 8, 8, 2]]])

In [46]:
x2.ndim

2

In [47]:
x2.shape

(3, 4)

In [48]:
x2.size

12

In [49]:
x2.dtype

dtype('int32')

In [50]:
x3.itemsize

4

In [52]:
x3.nbytes

240

In [53]:
#accessing the 2D array
x2=np.random.randint(10,size=(3,4))
x2

array([[3, 2, 0, 8],
       [8, 3, 8, 2],
       [8, 4, 3, 0]])

In [54]:
x2[:2,:3]

array([[3, 2, 0],
       [8, 3, 8]])

In [55]:
x2[1:3,:2:3]

array([[8],
       [8]])

In [56]:
x2[:,0] # notice this one

array([3, 8, 8])

In [58]:
# sub array as no-copy view
sub_x2=x2[:2,:2]
sub_x2

array([[3, 2],
       [8, 3]])

In [59]:
sub_x2[0,0]=19
sub_x2

array([[19,  2],
       [ 8,  3]])

In [60]:
sub_x2_copy=sub_x2[:2,:2].copy()
sub_x2_copy

array([[19,  2],
       [ 8,  3]])

In [61]:
#reshaping of array
#reshape(x,y)-----
a=np.arange(1,10).reshape(3,3)

In [62]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# some errors teach you a lot - so enjoy these errors 

In [24]:


a=np.arange(1,9).reshape(3,4)
a

ValueError: cannot reshape array of size 8 into shape (3,4)

In [25]:
a=np.arange([1,2,3]).reshape(1,3)
a

# learn from these errors 

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [69]:
a=np.array([1,2,3])
a.reshape(1,3)

array([[1, 2, 3]])

In [71]:
a[np.newaxis,:] # row vvector via newaxis

array([[1, 2, 3]])